/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    collider: THREE.Mesh;
    frames: THREE.Mesh;
    structure: THREE.Mesh;
  };
  materials: {
    ["frames.mat"]: THREE.MeshStandardMaterial;
    ["structure.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/floor3-1623708125/floor3.glb.gz";

export default function Model(
  props: { night?: boolean } & JSX.IntrinsicElements["group"]
) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Gotham_03glb">
          <mesh
            name="collider"
            geometry={nodes.collider.geometry}
            material={nodes.collider.material}
          />
          <mesh
            name="frames"
            geometry={nodes.frames.geometry}
            material={materials["frames.mat"]}
          />
          <mesh
            name="structure"
            geometry={nodes.structure.geometry}
            material={materials["structure.mat"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
