/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    collider: THREE.Mesh;
    doors: THREE.Mesh;
    windows: THREE.Mesh;
    couch: THREE.Mesh;
    table: THREE.Mesh;
    stilts: THREE.Mesh;
    fans: THREE.Mesh;
    misc: THREE.Mesh;
    terrain: THREE.Mesh;
    wallsa: THREE.Mesh;
    pedestal: THREE.Mesh;
    balconyrailing: THREE.Mesh;
    floor: THREE.Mesh;
    railing: THREE.Mesh;
    supports: THREE.Mesh;
    balcony: THREE.Mesh;
    balconysupport: THREE.Mesh;
    wallsb: THREE.Mesh;
  };
  materials: {
    ["doors.mat"]: THREE.MeshStandardMaterial;
    ["windows.mat"]: THREE.MeshStandardMaterial;
    ["couch.mat"]: THREE.MeshStandardMaterial;
    ["table.mat"]: THREE.MeshStandardMaterial;
    ["stilts.mat"]: THREE.MeshStandardMaterial;
    ["fans.mat"]: THREE.MeshStandardMaterial;
    ["misc.mat"]: THREE.MeshStandardMaterial;
    ["terrain.mat"]: THREE.MeshStandardMaterial;
    ["wall.a2.mat"]: THREE.MeshStandardMaterial;
    ["pedestal.mat"]: THREE.MeshStandardMaterial;
    ["balcony.railing.mat"]: THREE.MeshStandardMaterial;
    ["floor2.mat"]: THREE.MeshStandardMaterial;
    ["railing.mat"]: THREE.MeshStandardMaterial;
    ["supports2.mat"]: THREE.MeshStandardMaterial;
    ["balcony.mat"]: THREE.MeshStandardMaterial;
    ["balcony.support.mat"]: THREE.MeshStandardMaterial;
    ["wall.b2.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Musehq-1619942991/musehq_02.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  useTrimeshCollision(
    (nodes.collider.geometry as BufferGeometry).clone().scale(3, 3, 3)
  );

  return (
    <group ref={group} {...props} dispose={null} name="musehq" scale={3}>
      <group name="Scene">
        <group name="musehq_02glb">
          {/*<mesh*/}
          {/*  name="collider"*/}
          {/*  geometry={nodes.collider.geometry}*/}
          {/*  material={nodes.collider.material}*/}
          {/*/>*/}
          <mesh
            name="doors"
            geometry={nodes.doors.geometry}
            material={materials["doors.mat"]}
          />
          <mesh
            name="windows"
            geometry={nodes.windows.geometry}
            material={materials["windows.mat"]}
          />
          <mesh
            name="couch"
            geometry={nodes.couch.geometry}
            material={materials["couch.mat"]}
          />
          <mesh
            name="table"
            geometry={nodes.table.geometry}
            material={materials["table.mat"]}
          />
          <mesh
            name="stilts"
            geometry={nodes.stilts.geometry}
            material={materials["stilts.mat"]}
          />
          <mesh
            name="fans"
            geometry={nodes.fans.geometry}
            material={materials["fans.mat"]}
            position={[0, 6.3767, -0.0104]}
            rotation={[2.3937, 0, 0]}
          />
          <mesh
            name="misc"
            geometry={nodes.misc.geometry}
            material={materials["misc.mat"]}
          />
          <mesh
            name="terrain"
            geometry={nodes.terrain.geometry}
            material={materials["terrain.mat"]}
          />
          <mesh
            name="wallsa"
            geometry={nodes.wallsa.geometry}
            material={materials["wall.a2.mat"]}
          />
          <mesh
            name="pedestal"
            geometry={nodes.pedestal.geometry}
            material={materials["pedestal.mat"]}
          />
          <mesh
            name="balconyrailing"
            geometry={nodes.balconyrailing.geometry}
            material={materials["balcony.railing.mat"]}
          />
          <mesh
            name="floor"
            geometry={nodes.floor.geometry}
            material={materials["floor2.mat"]}
          />
          <mesh
            name="railing"
            geometry={nodes.railing.geometry}
            material={materials["railing.mat"]}
          />
          <mesh
            name="supports"
            geometry={nodes.supports.geometry}
            material={materials["supports2.mat"]}
          />
          <mesh
            name="balcony"
            geometry={nodes.balcony.geometry}
            material={materials["balcony.mat"]}
          />
          <mesh
            name="balconysupport"
            geometry={nodes.balconysupport.geometry}
            material={materials["balcony.support.mat"]}
          />
          <mesh
            name="wallsb"
            geometry={nodes.wallsb.geometry}
            material={materials["wall.b2.mat"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
