/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    table: THREE.Mesh;
    supports: THREE.Mesh;
    wallsa: THREE.Mesh;
    wallsb: THREE.Mesh;
    floor: THREE.Mesh;
    windows: THREE.Mesh;
    stairs: THREE.Mesh;
    doors: THREE.Mesh;
    railing: THREE.Mesh;
    misc: THREE.Mesh;
  };
  materials: {
    ["table.2"]: THREE.MeshStandardMaterial;
    ["supports.1"]: THREE.MeshStandardMaterial;
    ["walls.a"]: THREE.MeshStandardMaterial;
    ["walls.b"]: THREE.MeshStandardMaterial;
    floor: THREE.MeshStandardMaterial;
    windows: THREE.MeshStandardMaterial;
    stairs: THREE.MeshStandardMaterial;
    doors: THREE.MeshStandardMaterial;
    railing: THREE.MeshStandardMaterial;
    misc: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Saas-1617159865/saas_00.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position-y={-0.02} scale={[3.5, 3.5, 3.5]}>
        <mesh
          name="table"
          material={materials["table.2"]}
          geometry={nodes.table.geometry}
        />
        <mesh
          name="supports"
          material={materials["supports.1"]}
          geometry={nodes.supports.geometry}
        />
        <mesh
          name="wallsa"
          material={materials["walls.a"]}
          geometry={nodes.wallsa.geometry}
        />
        <mesh
          name="wallsb"
          material={materials["walls.b"]}
          geometry={nodes.wallsb.geometry}
        />
        <mesh
          name="floor"
          material={materials.floor}
          geometry={nodes.floor.geometry}
        />
        <mesh
          name="windows"
          material={materials.windows}
          geometry={nodes.windows.geometry}
        />
        <mesh
          name="stairs"
          material={materials.stairs}
          geometry={nodes.stairs.geometry}
        />
        <mesh
          name="doors"
          material={materials.doors}
          geometry={nodes.doors.geometry}
        />
        <mesh
          name="railing"
          material={materials.railing}
          geometry={nodes.railing.geometry}
        />
        <mesh
          name="misc"
          material={materials.misc}
          geometry={nodes.misc.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
