/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    gator: THREE.Mesh;
  };
  materials: {
    ["gator.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/gatorhead-1617845675/gatorhead.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation-y={0.88}>
        <mesh
          name="gator"
          material={materials["gator.mat"]}
          geometry={nodes.gator.geometry}
          rotation={[0, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
