/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    ghost: THREE.Mesh;
  };
  materials: {
    ["ghost.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/ghost-1617672835/ghost.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  materials["ghost.mat"].metalness = 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="ghost"
          material={materials["ghost.mat"]}
          geometry={nodes.ghost.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
