/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    cat: THREE.Mesh;
  };
  materials: {
    ["cat.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/moneycat-1617672845/moneycat.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  materials["cat.mat"].metalness = 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="cat"
          material={materials["cat.mat"]}
          geometry={nodes.cat.geometry}
          scale={[100, 100, 100]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
