/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useContext, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { Interactable } from "spacesvr";
import { ShopContext } from "../index";

type GLTFResult = GLTF & {
  nodes: {
    Cash_Register_node: THREE.Mesh;
  };
  materials: {
    ["03___Default"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/register-1619677702/register.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  const { cart } = useContext(ShopContext);
  return (
    <group name="register" ref={group} {...props} dispose={null}>
      <group
        position={[2, 0.65, 5.35]}
        rotation-y={-Math.PI / 2}
        scale={[0.015, 0.015, 0.015]}
      >
        <group>
          <Interactable
            onClick={() => cart.url && window.open(cart.url, "_blank")}
          >
            <mesh name="hitbox">
              <boxBufferGeometry attach="geometry" args={[5, 5, 5]} />
              <meshBasicMaterial attach="material" color="blue" wireframe />
            </mesh>
          </Interactable>
          <mesh
            name="Cash_Register_node"
            geometry={nodes.Cash_Register_node.geometry}
            material={materials["03___Default"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
