/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useContext, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { Interactable, useTrimeshCollision } from "spacesvr";
import { ShopContext } from "../index";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Plane146: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/register-1619748810/register.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  const { cart } = useContext(ShopContext);

  materials["Material"].metalness = 0;

  return (
    <group
      ref={group}
      dispose={null}
      position={[2, 0.65, 5.35]}
      rotation-y={-Math.PI}
      {...props}
    >
      <Interactable onClick={() => cart.url && window.open(cart.url, "_blank")}>
        <mesh position={[0, 0.225, 0.1]} name="hitbox">
          <boxBufferGeometry args={[0.67, 0.56, 0.65]} />
          <meshBasicMaterial opacity={0} transparent />
        </mesh>
      </Interactable>
      <group scale={2} name="Register2">
        <mesh
          name="Plane146"
          geometry={nodes.Plane146.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
