/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    floors: THREE.Mesh;
    additions: THREE.Mesh;
    hallway: THREE.Mesh;
    box: THREE.Mesh;
    collider: THREE.Mesh;
  };
  materials: {
    BLACK: THREE.MeshStandardMaterial;
    WHITE: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/lucid-1626714130/lucidmonday_00.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/lucidmonday_00.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[80, 80, 80]}>
        <group position={[0, -0.005, 0]}>
          <mesh
            name="floors"
            material={materials.BLACK}
            geometry={nodes.floors.geometry}
          />
          <mesh
            name="additions"
            material={materials.WHITE}
            geometry={nodes.additions.geometry}
          />
          <mesh
            name="hallway"
            material={materials.BLACK}
            geometry={nodes.hallway.geometry}
          />
          <mesh
            name="box"
            material={materials.WHITE}
            geometry={nodes.box.geometry}
          />
          <mesh
            name="collider"
            material={materials["default"]}
            geometry={nodes.collider.geometry}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
