/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    floors: THREE.Mesh;
    additions: THREE.Mesh;
    collider: THREE.Mesh;
  };
  materials: {
    BLACK: THREE.MeshStandardMaterial;
    WHITE: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/lucidmonday_02-1626737387/lucidmonday_02.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;

  useTrimeshCollision(
    (nodes.collider.geometry as BufferGeometry)
      .clone()
      .scale(0.8, 0.8, 0.8)
      .translate(0, -4, 0)
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.8}>
        <group position={[0, -5, 0]}>
          <mesh
            name="floors"
            geometry={nodes.floors.geometry}
            material={materials.BLACK}
          />
          <mesh
            name="additions"
            geometry={nodes.additions.geometry}
            material={materials.WHITE}
          />
          {/* <mesh name="collider" geometry={nodes.collider.geometry} material={nodes.collider.material} /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
