/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { Interactable, Floating } from "spacesvr";
import { useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    floors: THREE.Mesh;
    additions: THREE.Mesh;
    albums: THREE.Mesh;
    ["hitbox-20"]: THREE.Mesh;
    ["hitbox-21"]: THREE.Mesh;
    ["hitbox-22"]: THREE.Mesh;
    ["hitbox-23"]: THREE.Mesh;
    ["hitbox-24"]: THREE.Mesh;
    ["hitbox-25"]: THREE.Mesh;
    collider: THREE.Mesh;
  };
  materials: {
    BLACK: THREE.MeshStandardMaterial;
    WHITE: THREE.MeshStandardMaterial;
    ALBUMS: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/lucidmonday_07-1627278757/lucidmonday_07.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;

  useTrimeshCollision(
    (nodes.collider.geometry as BufferGeometry)
      .clone()
      .scale(0.8, 0.8, 0.8)
      .translate(0, -4, 0)
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.8}>
        <group position={[0, -5, 0]}>
          <mesh
            name="floors"
            geometry={nodes.floors.geometry}
            material={materials.BLACK}
          />
          <mesh
            name="additions"
            geometry={nodes.additions.geometry}
            material={materials.WHITE}
          />
          <Floating height={0.1}>
            <mesh
              name="albums"
              geometry={nodes.albums.geometry}
              material={materials.ALBUMS}
            />
          </Floating>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm020",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-20"
              geometry={nodes["hitbox-20"].geometry}
              material={nodes["hitbox-20"].material}
              visible={false}
            />
          </Interactable>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm021",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-21"
              geometry={nodes["hitbox-21"].geometry}
              material={nodes["hitbox-21"].material}
              visible={false}
            />
          </Interactable>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm022",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-22"
              geometry={nodes["hitbox-22"].geometry}
              material={nodes["hitbox-22"].material}
              visible={false}
            />
          </Interactable>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm023",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-23"
              geometry={nodes["hitbox-23"].geometry}
              material={nodes["hitbox-23"].material}
              visible={false}
            />
          </Interactable>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm024",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-24"
              geometry={nodes["hitbox-24"].geometry}
              material={nodes["hitbox-24"].material}
              visible={false}
            />
          </Interactable>
          <Interactable
            onClick={() => {
              window.open(
                "https://soundcloud.com/lucidmonday/sets/lm025",
                "_blank"
              );
            }}
          >
            <mesh
              name="hitbox-25"
              geometry={nodes["hitbox-25"].geometry}
              material={nodes["hitbox-25"].material}
              visible={false}
            />
          </Interactable>
          {/* <mesh name="collider" geometry={nodes.collider.geometry} material={nodes.collider.material} /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
