/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    lucid: THREE.Mesh;
    ears: THREE.Mesh;
    mouth: THREE.Mesh;
    rainbow: THREE.Mesh;
  };
  materials: {
    ["lucid.mat"]: THREE.MeshStandardMaterial;
    ["ears.mat"]: THREE.MeshStandardMaterial;
    ["mouth.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/monmon_02-1627007074/monmon_02.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[12, 12, 12]}>
        <mesh
          name="lucid"
          geometry={nodes.lucid.geometry}
          material={nodes.lucid.material}
        />
        <mesh
          name="ears"
          geometry={nodes.ears.geometry}
          material={materials["ears.mat"]}
        />
        <mesh
          name="mouth"
          geometry={nodes.mouth.geometry}
          material={materials["mouth.mat"]}
        />
        <mesh
          name="rainbow"
          geometry={nodes.rainbow.geometry}
          material={nodes.rainbow.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
