/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    lucid: THREE.Mesh;
  };
  materials: {
    ["lucid.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/monmon_01-1626770328/monmon_01.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[12, 12, 12]}>
        <mesh
          name="lucid"
          geometry={nodes.lucid.geometry}
          material={materials["lucid.mat"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILEURL);
