/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Plane001: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/palmtree-1622667944/palmtree.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  materials["Material.001"].metalness = 0.68;
  materials["Material.002"].metalness = 0.75;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={0.15}>
        <group name="uploads_files_2435215_Palm+Treesglb">
          <group
            name="Cylinder001"
            position={[0, 5.8427, 4.4944]}
            scale={[0.161, 6.321, 0.161]}
          >
            <mesh
              name="Cylinder001_1"
              geometry={nodes.Cylinder001_1.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              name="Cylinder001_2"
              geometry={nodes.Cylinder001_2.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials["Material.001"]}
            position={[-0.071, 12.3418, 6.1154]}
            rotation={[-0.284, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
