/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { Spinning } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    lucid: THREE.Mesh;
    ears: THREE.Mesh;
    rainbow: THREE.Mesh;
  };
  materials: {
    ["lucid.mat"]: THREE.MeshStandardMaterial;
    ["ears.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILEURL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/monmon_06-1627252426/monmon_06.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILEURL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <Spinning xSpeed={1} ySpeed={1} zSpeed={0.5}>
        <group scale={[12, 12, 12]}>
          <group>
            <mesh
              name="lucid"
              geometry={nodes.lucid.geometry}
              material={materials["lucid.mat"]}
            />
            <mesh
              name="ears"
              geometry={nodes.ears.geometry}
              material={materials["ears.mat"]}
            />
            <mesh name="rainbow" geometry={nodes.rainbow.geometry}>
              <meshNormalMaterial />
            </mesh>
          </group>
        </group>
      </Spinning>
    </group>
  );
}

useGLTF.preload(FILEURL);
