/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    structure1: THREE.Mesh;
  };
  materials: {
    ["structure.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/alto-1609378760/alto_00.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  // materials["structure.mat"].color = new THREE.Color("blue");

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="structure1"
          material={materials["structure.mat"]}
          geometry={nodes.structure1.geometry}
          position={[0.0024, 1.643, -1.0387]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
