/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    structure: THREE.Mesh;
  };
  materials: {
    ["structure.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://spaces-gallery-assets.s3-us-west-1.amazonaws.com/models/renaissance-1609393927/alto_01.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="structure"
          material={materials["structure.mat"]}
          geometry={nodes.structure.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
