/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";
import { Color } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Object025: THREE.Mesh;
  };
  materials: {
    ["02 - Default"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Jukebox-1608775010/jukebox-2.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;

  materials["02 - Default"].emissiveMap = materials["02 - Default"].map;
  materials["02 - Default"].emissive = new Color(0x333333);
  materials["02 - Default"].emissiveIntensity = 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[0.35, 0.35, 0.35]}>
        <mesh
          name="Object025"
          material={materials["02 - Default"]}
          geometry={nodes.Object025.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
