/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    Cube2: THREE.Mesh;
    Cube1: THREE.Mesh;
    Extrude1: THREE.Mesh;
  };
  materials: {
    ["Logo.color"]: THREE.MeshStandardMaterial;
    ["Button.box"]: THREE.MeshStandardMaterial;
    ["Linkedin.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Spotify-1608597760/spotify.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();

  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;

  materials["Logo.color"].metalness = 0.1;
  materials["Button.box"].metalness = 0.1;
  materials["Linkedin.mat"].metalness = 0.1;

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="Cube2"
          material={materials["Logo.color"]}
          geometry={nodes.Cube2.geometry}
        />
        <mesh
          name="Cube1"
          material={materials["Button.box"]}
          geometry={nodes.Cube1.geometry}
        />
        <mesh
          name="Extrude1"
          material={materials["Linkedin.mat"]}
          geometry={nodes.Extrude1.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
