/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL, useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    collider: THREE.Mesh;
    gods: THREE.Mesh;
    spawn: THREE.Mesh;
    information: THREE.Mesh;
    stairs: THREE.Mesh;
    doorways: THREE.Mesh;
    structure: THREE.Mesh;
    archway: THREE.Mesh;
    terrain: THREE.Mesh;
  };
  materials: {
    ["spawn.mat"]: THREE.MeshStandardMaterial;
    ["information.mat"]: THREE.MeshStandardMaterial;
    ["stairs.mat"]: THREE.MeshStandardMaterial;
    ["doorways.mat"]: THREE.MeshStandardMaterial;
    ["structure.mat"]: THREE.MeshStandardMaterial;
    ["archway.mat"]: THREE.MeshStandardMaterial;
    ["terrain.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Alto-1611297626/alto_08.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;

  useTrimeshCollision(
    (nodes.collider.geometry as BufferGeometry)
      .clone()
      .scale(12, 12, 12)
      .translate(0, -36.69, 0)
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group position-y={-36.69}>
        <group scale={[12, 12, 12]}>
          <mesh
            name="gods"
            material={nodes.gods.material}
            geometry={nodes.gods.geometry}
            rotation={[0, 0, 0]}
          />
          <mesh
            name="spawn"
            material={materials["spawn.mat"]}
            geometry={nodes.spawn.geometry}
          />
          <mesh
            name="information"
            material={materials["information.mat"]}
            geometry={nodes.information.geometry}
            rotation={[0, 0, 0]}
          />
          <mesh
            name="stairs"
            material={materials["stairs.mat"]}
            geometry={nodes.stairs.geometry}
          />
          <mesh
            name="doorways"
            material={materials["doorways.mat"]}
            geometry={nodes.doorways.geometry}
          />
          <mesh
            name="structure"
            material={materials["structure.mat"]}
            geometry={nodes.structure.geometry}
          />
          <mesh
            name="archway"
            material={materials["archway.mat"]}
            geometry={nodes.archway.geometry}
            rotation={[0, 0, 0]}
          />
          <mesh
            name="terrain"
            material={materials["terrain.mat"]}
            geometry={nodes.terrain.geometry}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
