/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { MutableRefObject } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    among_us_001: THREE.Mesh;
  };
  materials: {
    ["red color"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/amongus-1611130356/amongus.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="among_us_001"
          geometry={nodes.among_us_001.geometry}
          material={nodes.among_us_001.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
