/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useLoader } from "react-three-fiber";

type GLTFResult = GLTF & {
  nodes: {
    among_us_001: THREE.Mesh;
  };
  materials: {
    ["red color"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/amongus-1611130356/amongus.glb";

const Model = React.forwardRef(
  (props: JSX.IntrinsicElements["group"] & any, ref) => {
    // const group = useRef<THREE.Group>()
    const { texture } = props;
    const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
    // const texture = useLoader(THREE.TextureLoader, "https://d27rt3a60hh1lx.cloudfront.net/content/muse.place/renaissance/cubehm.jpg");

    return (
      <group ref={ref} {...props} dispose={null}>
        <group name="Scene">
          <mesh
            name="among_us_001"
            // material={materials['red color']}
            geometry={nodes.among_us_001.geometry}
          >
            <meshStandardMaterial
              attach="material"
              displacementMap={texture}
              displacementScale={1}
            />
          </mesh>
        </group>
      </group>
    );
  }
);

useGLTF.preload(FILE_URL);
export default Model;
