/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
// @ts-ignore
import { animated, useSpring } from "react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    tophandle: THREE.Mesh;
    paper: THREE.Mesh;
    bottomhandle: THREE.Mesh;
  };
  materials: {
    handlemat: THREE.MeshStandardMaterial;
    papermat: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/ScrollNoDraco-1618369852/scene.glb.gz";

type Props = {
  open: boolean;
} & JSX.IntrinsicElements["group"];

export default function Model(props: Props) {
  const { open } = props;

  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  const { posY, scale } = useSpring({
    posY: open ? 0 : 0.75 * 17.5,
    scale: open ? 1 : 0.1,
    config: {
      mass: 1,
      tension: 110,
      friction: 30,
    },
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <animated.group
        name="Scene"
        scale={[0.07, 0.07, 0.07]}
        rotation-y={Math.PI}
      >
        <mesh
          name="tophandle"
          material={materials.handlemat}
          geometry={nodes.tophandle.geometry}
        />
        <animated.mesh
          name="paper"
          material={materials.papermat}
          geometry={nodes.paper.geometry}
          scale-y={scale}
        />
        <animated.mesh
          name="bottomhandle"
          material={materials.handlemat}
          geometry={nodes.bottomhandle.geometry}
          position-y={posY}
        />
      </animated.group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
