/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    tophandle: THREE.Mesh;
    paper: THREE.Mesh;
    bottomhandle: THREE.Mesh;
  };
  materials: {
    handlemat: THREE.MeshStandardMaterial;
    papermat: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Scroll-1611622181/scroll28.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[0.1, 0.1, 0.1]}>
        <mesh
          name="tophandle"
          material={materials.handlemat}
          geometry={nodes.tophandle.geometry}
        />
        <mesh
          name="paper"
          material={materials.papermat}
          geometry={nodes.paper.geometry}
        />
        <mesh
          name="bottomhandle"
          material={materials.handlemat}
          geometry={nodes.bottomhandle.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
