/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    nifty: THREE.Mesh;
  };
  materials: {
    ["nifty.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/NiftyButton-1627352733/nifty_button.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null} scale={0.2} position-x={-0.05}>
      <group>
        <mesh
          name="nifty"
          geometry={nodes.nifty.geometry}
          material={materials["nifty.mat"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
