/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    opensea: THREE.Mesh;
  };
  materials: {
    ["opensea.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/OpenseaButton-1627352790/opensea_button.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.2}
      position-z={0.05}
      position-x={-0.05}
    >
      <group>
        <mesh
          name="opensea"
          geometry={nodes.opensea.geometry}
          material={materials["opensea.mat"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
