/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    tiktok: THREE.Mesh;
  };
  materials: {
    ["tiktok.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/TiktokButton-1627352908/tiktok_button.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null} scale={0.2}>
      <group>
        <mesh
          name="tiktok"
          geometry={nodes.tiktok.geometry}
          material={materials["tiktok.mat"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
