/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { Mesh, Vector2 } from "three";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    rough_plastic: THREE.MeshStandardMaterial;
    smooth_plastic: THREE.MeshStandardMaterial;
    demi_rough_plastic: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://dwvo2npct47gg.cloudfront.net/models/awge-space/Joystick-1617698121/joystick_01.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  const stick = useRef<Mesh>();
  const ball = useRef<Mesh>();
  const joystickEl = useRef<HTMLDivElement>();
  const dummy = useMemo(() => new Vector2(), []);

  const amount = Math.PI * 0.1;

  useFrame(() => {
    if (!joystickEl.current || !stick.current || !ball.current) return;

    const top = parseInt(joystickEl.current.style.top.replace("px", ""));
    const left = -1 * parseInt(joystickEl.current.style.left.replace("px", ""));

    const angle = dummy.set(top, left).angle();

    stick.current.rotation.x = amount * Math.cos(angle);
    stick.current.rotation.z = amount * Math.sin(angle);

    ball.current.rotation.x = amount * Math.cos(angle);
    ball.current.rotation.z = amount * Math.sin(angle);
  });

  useEffect(() => {
    const el = document.getElementsByClassName("nipple")[0];
    joystickEl.current = el.children[1] as HTMLDivElement;
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[1.4, 1.4, 1.4]}>
        <group position-y={2}>
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials.Material}
            position-y={-2}
            ref={ball}
          />
        </group>
        <mesh
          name="Plane_1"
          geometry={nodes.Plane_1.geometry}
          material={materials.smooth_plastic}
          ref={stick}
        />
        <group name="joystick_body" position-y={0.1}>
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.rough_plastic}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials.demi_rough_plastic}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
