/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Hemp_plant_01: THREE.Mesh;
  };
  materials: {
    ["Hemp_plant.002"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/WeedPlant-1620877818/weed_plant.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Hemp_plant_01"
          geometry={nodes.Hemp_plant_01.geometry}
          material={materials["Hemp_plant.002"]}
          rotation-x={Math.PI / 2}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
